---
- hosts: all
  user: ec2-user
  gather_facts: yes
  vars:
    - zabbix_agent_state: present
    - zabbix_agent_status: enabled
  roles:
    - { role: zabbix-agent-deploy }
    - { role: zabbix-agent-registration }
