---
- hosts: all
  user: ec2-user
  gather_facts: yes
  vars:
    - zabbix_agent_state: absent
    - zabbix_agent_status: disabled
  roles:
    - { role: zabbix-agent-remove }
    - { role: zabbix-agent-registration }
