---
- hosts: all
  user: ec2-user
  gather_facts: yes
  vars:
    - zabbix_agent_register_server: true
    - zabbix_agent_state: absent    #present|absent
    - zabbix_agent_status: disabled #enabled|disabled
  roles:
    - { role: zabbix-agent-remove }
    - { role: zabbix-agent-registration }
