---
zabbix_agent_url: http://zabbix.traderfrance.com/zabbix/
zabbix_agent_user: ansible
zabbix_agent_password: ansible
zabbix_agent_template:
  - Template OS Linux
zabbix_agent_hostgroup:
  - Linux servers
#  - Discovered hosts
#  - Joubert-Hosts
#  - DBs MySQL
#  - AWS-Other
#  - AutoScaleHosts
zabbix_agent_interface_ip: {{ ansible_default_ipv4.address }}
zabbix_server: {{ zabbix_server_ip }}
